version: '3.7'

services:
    webapp-server:
      build:
        context: .
        dockerfile: Dockerfile
      image: tarem-api-server-img
      container_name: tarem-api-express
      volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
      ports:
        - "3001:3001"
      depends_on:
        - mongo
      env_file: .env
      environment:
        - MONGODB_URI=$MONGODB_URI
    mongo:
      image: mongo
      container_name: tarem-api-mongodb
      ports:
        - "27017:27017"